name: supervised-learning-workshop
channels:
  - conda-forge
  - anaconda
dependencies:
  - pip:
    - matplotlib==2.2.3
    - missingno==0.4.2
    - numpy==1.17.4
    - pandas==1.0.3
    - seaborn==0.10.0
    - scikit-learn==0.21.3
    - statsmodels==0.11.0
    - urllib3==1.25.8
  - python-graphviz
  - pydot
